### ISSUE TITLE
Unable to connect to LDAP after restart

### ISSUE THREAD

**Issue by iromli** [GluuFederation/docker-oxshibboleth#2]
Restarting oxShibboleth container ended up in service failure.

## Usecase

This is a typical `ldap.properties` file:

```
## Connection properties ##
idp.authn.LDAP.ldapURL = ldaps://ldap:1636
idp.authn.LDAP.useStartTLS = false
idp.authn.LDAP.useSSL = true

## SSL configuration, either jvmTrust, certificateTrust, or keyStoreTrust
idp.authn.LDAP.sslConfig = certificateTrust
## If using certificateTrust above, set to the trusted certificate's path
idp.authn.LDAP.trustCertificates = /etc/certs/opendj.crt
```

where `ldap:1636` is the LDAP service's host and port.

Given that CN in `/etc/certs/opendj.crt` is not `ldap` (`config-init` generates this cert using `CN=<domain>`), oxShibboleth throws error about host and CN mismatch, which will prevent oxShibboleth to run and load Shibboleth config files properly.

**Comment by iromli** [comment]
Somehow even when CN is modified to match `idp.authn.LDAP.ldapURL` value, the error still occured. A workaround to this issue is to re-deploy oxShibboleth. Or if the scheduler (swarm, compose, k8s) has scaling feature, use the command to scale down to 0 and up.

**Comment by iromli** [comment]
Adding Subject Alt Name in certificate should fix the issue with CN mismatch.

```
# example-openssl.cnf
[alt_names]
DNS.1 = ldap
```

Note, we can still use `CN=<domain>`. This value is checked only if there's no matching alt names.

**Comment by iromli** [comment]
In terms of containers startup order, `config-init` and `opendj`/`openldap` is the best place to generate cert with SAN (Subject Alt Name). Though there are few things to consider to:

## Generating cert in config-init

Pros:
- only run once before deploying other containers

Cons:
- we don't know the name of DNS that need to be added as SAN

## Generating cert in OpenDJ/OpenLDAP

Pros:
- we know the name of DNS that need to be added as SAN

Cons:
- requires a solid flow to make sure cert is not regenerated when container restarted or scaled; though we can create a flag in config backend or file (similar to `/flag/ldap_initialized`) to mark whether cert already updated with SAN

**Comment by iromli** [comment]
> I think we could introduce a flag similar to what you mentioned, but instead of a path, we could introspect the certificate in entrypoint.py to see if it has the proper ldap hostname.

Good idea. We can check whether a SAN has been added (where the name is based on user-input). If it's there, skip the cert regeneration.

**Comment by afroDC** [comment]
Right we can take [this information](https://github.com/GluuFederation/gluu-docker/blob/master/examples/single-host/docker-compose.yml#L123) and utilize it to our benefit. If the SAN inside shibboleth is wrong, as in a user changed their ldap hostname for some reason, it could detect and create a new cert.

> Also would the LDAP container need to add the new cert to it's truststore or would the Shibboleth container be the only one? It seems like it would need to be in both for proper functionality.

I still think we have to figure out this part through functional testing @iromli

**Comment by iromli** [comment]
Certs are regenerated in OpenDJ container. I don't see any required modification in oxShibboleth for now. 

This is an example:
- given OpenDJ service set as `ldap`, oxShibboleth `GLUU_LDAP_URL` must be pointed to `ldap:1636`
- if somehow OpenDJ service change the name to `opendj` (a new domain in cert SAN will be generated), oxShibboleth `GLUU_LDAP_URL` must be pointed to `opendj:1636` which in turn triggers scheduler to re-deploy container

**Comment by afroDC** [comment]
How would the scheduler know to redeploy?

Also should the opendj cert be updated in the configuration as well whenever this happens?

**Comment by iromli** [comment]
> How would the scheduler know to redeploy?

In Kubernetes, if you change `.yaml` file, running `kubectl apply -f <yaml-file>` will re deploy the container. Same with docker-compose file.

> Also should the opendj cert be updated in the configuration as well whenever this happens?

Yes, cert is updated in config backend since we parse and compare the SAN to avoid having regenerating all the times.

**Comment by afroDC** [comment]
> The flow would be when running OpenDJ container, first it checks GLUU_CERT_ALT_NAME env var. 

Here the  `GLUU_CERT_ALT_NAME` variable would be the name of the container?

**Comment by iromli** [comment]
It can be container name, hostname, service name, or even network alias. Depends on how the container is deployed in which network, but as long the name is resolvable via DNS, it should work.

`docker-compose` for singlehost example:

```yaml
services:
  ldap:
    image: gluufederation/opendj:latest
    environment:
      # alt name matches the service name
      - GLUU_CERT_ALT_NAME=ldap
```

or for Swarm Mode:

```yaml
services:
  ldap_manager:
    image: gluufederation/opendj:latest
    networks:
      gluu:
        aliases:
          - ldap.server
    environment:
      # alt name matches network alias
      - GLUU_CERT_ALT_NAME=ldap.server
```

For Kubernetes:

```yaml
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: opendj-init
spec:
  serviceName: opendj
  template:
    containers:
      - name: opendj
        image: 'gluufederation/opendj:latest'
        env:
          - name: GLUU_CERT_ALT_NAME
            # alt name matches service name
            value: "opendj"
```
