### ISSUE TITLE
Not possible to access logs and/or switch logging verbosity levels in IDP

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/docker-oxshibboleth#47]
Description:

In my local test minikube deployment I'm unable to follow the standard procedure of enabling debug logging for IDP. OTB it's not possible to find where the IDP logs its operational information (ongoing flows, errors, audit logging etc), it can't be found either on STDOUT or in files inside the pod. 

Preconditions:

1. A freshly installed 4.4 deployment using Helm, according to the guide [here](https://gluu.org/docs/gluu-server/4.4/installation-guide/install-kubernetes/) with Minikube for k8s implementation.
2. Configured and working SAML TR (samltest.id is an option)

Steps to reproduce.

1. Prepare `values.yaml` with `oxshibboleth` global section edited as shown below:
  ```
    oxshibboleth:
    enabled: true
    appLoggers:
      idpLogTarget: "STDOUT"
      idpLogLevel: "DEBUG"
      scriptLogTarget: "FILE"
      scriptLogLevel: "INFO"
      auditStatsLogTarget: "FILE"
      auditStatsLogLevel: "INFO"
      consentAuditLogTarget: "FILE"
      consentAuditLogLevel: "INFO"
 ```
2. Run `# helm upgrade` with the `values.yaml` file
3. Restart the container to make sure the change has been picked up: `# kubectl rollout restart sts gluu-oxshibboleth`
4. Start a SAML flow and use either `# kubectl logs -f gluu-oxshibboleth-0` or (inside the pod) `# tail -F /opt/shibboleth-idp/logs/idp-process.log` to try and see the DEBUG logging for the flow

Result:

Despite the ENV variables seem to pick up the changed log level values (as shown by `# printenv | grep -i idp` inside the pod), IDP's logs can't be seen neither on STDOUT, nor in files inside the pod (though the files itself exist there).
